Repository LLNL/Aluminum, pull requests merged in 2022-06, with the labels that each got.

#147 Cleanup includes
  include/Al.hpp
  include/aluminum/cuda/cuda.hpp
  include/aluminum/cuda/gpu_status_flag.hpp
  include/aluminum/cuda/gpu_wait.hpp
  include/aluminum/cuda/streams.hpp
  include/aluminum/ht_impl.hpp
  include/aluminum/mempool.hpp
  include/aluminum/mpi/utils.hpp
  include/aluminum/mpi_impl.hpp
  include/aluminum/nccl_impl.hpp
  include/aluminum/profiling.hpp
  include/aluminum/progress.hpp
  include/aluminum/trace.hpp
  src/Al.cpp
  src/cuda/cuda.cpp
  src/cuda/gpu_status_flag.cpp
  src/cuda/gpu_wait.cpp
  src/cuda/streams.cpp
  src/mpi_impl.cpp
  src/nccl_impl.cpp
  src/profiling.cpp
  src/progress.cpp
  src/trace.cpp
Labels: enhancement

#150 Restore MPIAllreduceAlgorithm
  include/aluminum/mpi_impl.hpp
Labels: bug

#151 Fix a variety of build issues with ROCm 5
  benchmark/CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: bug, HIP/ROCm

#152 Better ROCm SMI support
  src/progress.cpp
Labels: bug
