Repository LLNL/Aluminum, pull requests merged in 2023-01, with the labels that each got.

#160 Flux Support
  benchmark/plot_benchmarks.py
  benchmark/run_benchmarks.py
  cmake/Al_config.hpp.in
  test/run_tests.py
  test/test_utils.hpp
Labels: enhancement

#161 HIP/ROCm stream memory operations
  CMakeLists.txt
  src/cuda/cuda.cpp
  src/cuda/gpu_status_flag.cpp
  src/cuda/helper_kernels.cu
Labels: enhancement

#163 Move away from JIT-hipified source code
  CMakeLists.txt
  benchmark/CMakeLists.txt
  benchmark/benchmark_events.cpp
  benchmark/benchmark_utils_ht.hpp
  benchmark/benchmark_utils_nccl.hpp
  benchmark/benchmark_waits.cpp
  benchmark/wait.cu
  benchmark/wait.hpp
  cmake/Al_config.hpp.in
  cmake/HipBuildSystem.cmake
  include/aluminum/cuda/cuda.hpp
  include/aluminum/cuda/cuda_mempool.hpp
  include/aluminum/cuda/events.hpp
  include/aluminum/cuda/gpu_status_flag.hpp
  include/aluminum/cuda/gpu_wait.hpp
  include/aluminum/cuda/helper_kernels.hpp
  include/aluminum/cuda/streams.hpp
  include/aluminum/cuda/sync_memory.hpp
  include/aluminum/ht/allgather.hpp
  include/aluminum/ht/allgatherv.hpp
  include/aluminum/ht/allreduce.hpp
  include/aluminum/ht/alltoall.hpp
  include/aluminum/ht/alltoallv.hpp
  include/aluminum/ht/barrier.hpp
  include/aluminum/ht/base_state.hpp
  include/aluminum/ht/bcast.hpp
  include/aluminum/ht/communicator.hpp
  include/aluminum/ht/gather.hpp
  include/aluminum/ht/gatherv.hpp
  include/aluminum/ht/pt2pt.hpp
  include/aluminum/ht/reduce.hpp
  include/aluminum/ht/reduce_scatter.hpp
  include/aluminum/ht/reduce_scatterv.hpp
  include/aluminum/ht/scatter.hpp
  include/aluminum/ht/scatterv.hpp
  include/aluminum/ht_impl.hpp
  include/aluminum/nccl_impl.hpp
  include/aluminum/profiling.hpp
  src/CMakeLists.txt
  src/cuda/cuda.cpp
  src/cuda/gpu_status_flag.cpp
  src/cuda/gpu_wait.cpp
  src/cuda/helper_kernels.cu
  src/cuda/streams.cpp
  src/ht_impl.cpp
  src/nccl_impl.cpp
  src/profiling.cpp
  src/progress.cpp
  test/CMakeLists.txt
  test/cuda_vector.hpp
  test/test_ops.cpp
  test/test_stream_mem_ops.cpp
  test/test_utils.hpp
  test/test_utils_ht.hpp
  test/test_utils_nccl.hpp
  util/CMakeLists.txt
Labels: HIP/ROCm

#164 ROCm-friendly example codes
  CMakeLists.txt
  examples/allreduce.cpp
  examples/hello_world.cpp
  examples/pingpong.cpp
  examples/utils.hpp
Labels: enhancement, HIP/ROCm

#165 Clean up the progress engine
  include/aluminum/ht/base_state.hpp
  include/aluminum/ht/pt2pt.hpp
  include/aluminum/mpi/allgather.hpp
  include/aluminum/mpi/allgatherv.hpp
  include/aluminum/mpi/allreduce.hpp
  include/aluminum/mpi/alltoall.hpp
  include/aluminum/mpi/alltoallv.hpp
  include/aluminum/mpi/barrier.hpp
  include/aluminum/mpi/base_state.hpp
  include/aluminum/mpi/bcast.hpp
  include/aluminum/mpi/gather.hpp
  include/aluminum/mpi/gatherv.hpp
  include/aluminum/mpi/pt2pt.hpp
  include/aluminum/mpi/reduce.hpp
  include/aluminum/mpi/reduce_scatter.hpp
  include/aluminum/mpi/reduce_scatterv.hpp
  include/aluminum/mpi/scatter.hpp
  include/aluminum/mpi/scatterv.hpp
  include/aluminum/mpi_cuda/rma.hpp
  include/aluminum/mpi_cuda/rma_ipc.hpp
  include/aluminum/mpi_cuda/rma_null.hpp
  include/aluminum/mpi_cuda/rma_self.hpp
  include/aluminum/mpi_impl.hpp
  include/aluminum/progress.hpp
  include/aluminum/state.hpp
  src/progress.cpp
Labels: enhancement

#166 Defer starting the progress engine
  include/aluminum/progress.hpp
  include/aluminum/tuning_params.hpp
  src/Al.cpp
  src/progress.cpp
Labels: enhancement

#167 Benchmark improvements
  benchmark/benchmark_ops.cpp
  benchmark/plot_benchmarks.py
  test/test_utils.hpp
Labels: enhancement

#168 Fix loads/store in MPSC queue
  include/aluminum/utils/mpsc_queue.hpp
Labels: bug

#169 Add CMake component checking for Aluminum
  cmake/AluminumConfig.cmake.in
Labels: enhancement
